#%RAML 1.0
annotationTypes:
  amf-serverDescription:
    type: any
  amf-exclusiveMinimum:
    type: any
  amf-binding:
    type: any
  amf-pattern:
    type: any
  amf-payloads:
    type: any
  amf-exclusiveMaximum:
    type: any
  amf-consumes:
    type: any
  amf-additionalProperties:
    type: any
  amf-or:
    type: any
  amf-url:
    type: any
  amf-externalDocs:
    type: any
  amf-flow:
    type: any
  amf-oasDeprecated:
    type: any
  amf-contact:
    type: any
  amf-multipleOf:
    type: any
  amf-xor:
    type: any
  amf-not:
    type: any
  amf-callbacks:
    type: any
  amf-produces:
    type: any
  amf-format:
    type: any
  amf-license:
    type: any
  amf-summary:
    type: any
  amf-responses:
    type: any
  amf-maximum:
    type: any
  amf-tags:
    type: any
  amf-dependencies:
    type: any
  amf-readOnly:
    type: any
  amf-tuple:
    type: any
  amf-examples:
    type: any
  amf-collectionFormat:
    type: any
  amf-termsOfService:
    type: any
  amf-servers:
    type: any
  amf-xone:
    type: any
  amf-defaultResponse:
    type: any
  amf-baseUriParameters:
    type: any
  amf-parameters:
    type: any
  amf-minimum:
    type: any
  amf-recursive:
    type: any
  amf-and:
    type: any
title: hra-sys-spec
version: 1.0.0
/rest/v1/hra-userrights:
  get:
    description: Get userrights data
    queryParameters:
      applicationName:
        description: enter application name
        required: true
        default: HRA
        enum:
          - HRA
        example:
          strict: false
          value: HRA
        type: string
      personId:
        description: enter correlationId/personId
        required: true
        example:
          strict: false
          value: 6004132
        type: string
      sourceSystem:
        description: enter sourcesystem
        required: false
        default: CHECK
        example:
          strict: false
          value: CHECK
        type: string
    headers:
      client_id:
        description: Authentication Client ID
        required: true
        type: string
      client_secret:
        description: Authentication Client Secret
        required: true
        type: string
      X-Conversation-Id:
        description: Optional Id managed by the caller/client that will be conveyed through DALI integration layer for the end to end traceability
        required: false
        type: string
      X-Correlation-Id:
        description: Required correlation Id conveyed all along the Mule transaction
        required: true
        type: string
    responses:
      "200":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: array
                items:
                  type: object
                  properties:
                    applicationName:
                      example:
                        strict: false
                        value: TBM/HRA
                      type: string
                      required: false
                    personId:
                      example:
                        strict: false
                        value: 6004132
                      type: string
                      required: false
                    entityType:
                      example:
                        strict: false
                        value: 5
                      type: string
                      required: false
                    organisationId:
                      example:
                        strict: false
                        value: 8010
                      type: string
                      required: false
                    droit:
                      example:
                        strict: false
                        value: Admin
                      type: string
                      required: false
                    module:
                      example:
                        strict: false
                        value: SECU
                      type: string
                      required: false
              error?:
                type: object
      "404":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:NOT_FOUND
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: record XXX not found
                    type: string
                    required: false
      "500":
        description: Server error
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:SERVER ERROR
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: server error
                    type: string
                    required: false
/rest/v1/formsPeopleassist:
  post:
    description: Endpoint description
    headers:
      client_id:
        description: Authentication Client ID
        required: true
        type: string
      client_secret:
        description: Authentication Client Secret
        required: true
        type: string
    body:
      application/json:
        type: object
        properties:
          requestId:
            example:
              strict: false
              value: c1611d90-b274-49c2-804c-3e0041e081d0
            type: string
          employeeId:
            example:
              strict: false
              value: "7026240"
            type: string
          firstName?:
            example:
              strict: false
              value: Prenom
            type: string
          lastName?:
            example:
              strict: false
              value: Nom
            type: string
          externalId?:
            example:
              strict: false
              value: "255450"
            type: string
          formData?:
            type: array
            items:
              type: object
              properties:
                fieldId:
                  example:
                    strict: false
                    value: dernier-jour-travaille
                  type: string
                values:
                  type: array
                  items:
                    example:
                      strict: false
                      value: 2024-06-10
                    type: string
          assignees?:
            type: array
            items:
              type: object
              properties:
                assigneeId:
                  example:
                    strict: false
                    value: e39edd30-1c9c-40be-8593-55c03861853c
                  type: string
                externalId:
                  example:
                    strict: false
                    value: USR_0000
                  type: string
                firstName:
                  example:
                    strict: false
                    value: Service
                  type: string
                lastName:
                  example:
                    strict: false
                    value: Paie
                  type: string
                email:
                  example:
                    strict: false
                    value: ddd@dd.com
                  type: string
    responses:
      "201":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
                properties:
                  status:
                    example:
                      strict: false
                      value: OK
                    type: string
              error?:
                type: object
      "404":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:NOT_FOUND
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: record XXX not found
                    type: string
                    required: false
/rest/v1/employees-history:
  get:
    description: Get employees history data
    queryParameters:
      employeeFileNumber:
        description: employeeFileNumber to filter on HRA system application
        required: true
        example:
          strict: false
          value: 641964
        type: number
      cdInfo:
        description: cdInfo to filter on HRA system application
        required: true
        example:
          strict: false
          value: ZYCA
        type: string
      eventDate:
        description: EventDate to filter on HRA system application format must be yyyy-MM-dd'T'HH:mm:ss.SSSXXXX
        required: true
        example:
          strict: false
          value: 2015-02-18T00:00:00.000+01:00
        type: string
    headers:
      client_id:
        description: Authentication Client ID
        required: true
        type: string
      client_secret:
        description: Authentication Client Secret
        required: true
        type: string
    responses:
      "200":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      companyCode:
                        example:
                          strict: false
                          value: "690"
                        type: string
                        required: false
                      employeeERPId:
                        example:
                          strict: false
                          value: employeeERPId
                        type: string
                        required: false
                      startDate:
                        example:
                          strict: false
                          value: startDate (yyyy-MM-dd)
                        type: string
                        required: false
                      endDate:
                        example:
                          strict: false
                          value: endDate (yyyy-MM-dd)
                        type: string
                        required: false
                      actionReason:
                        example:
                          strict: false
                          value: actionReason
                        type: string
                        required: false
                      category:
                        example:
                          strict: false
                          value: category
                        type: string
                        required: false
                      employeeArea:
                        example:
                          strict: false
                          value: employeeArea
                        type: string
                        required: false
                      employeeSubArea:
                        example:
                          strict: false
                          value: employeeSubArea
                        type: string
                        required: false
                      contractType:
                        example:
                          strict: false
                          value: contractType
                        type: string
                        required: false
                      contractEndDate:
                        example:
                          strict: false
                          value: contractEndDate (yyyy-MM-dd)
                        type: string
                        required: false
                      analyticalUnit:
                        example:
                          strict: false
                          value: analyticalUnit
                        type: string
                        required: false
                      employeeGroup:
                        example:
                          strict: false
                          value: employeeGroup
                        type: string
                        required: false
                      employeeSubGroup:
                        example:
                          strict: false
                          value: employeeSubGroup
                        type: string
                        required: false
                      lastName:
                        example:
                          strict: false
                          value: contractType
                        type: string
                        required: false
                      firstName:
                        example:
                          strict: false
                          value: contractEndDate
                        type: string
                        required: false
                      gender:
                        example:
                          strict: false
                          value: analyticalUnit
                        type: string
                        required: false
                      birthDate:
                        example:
                          strict: false
                          value: birthDate
                        type: string
                        required: false
                      nationality:
                        example:
                          strict: false
                          value: nationality
                        type: string
                        required: false
                      birthCountryCode:
                        example:
                          strict: false
                          value: birthCountryCode
                        type: string
                        required: false
                      birthState:
                        example:
                          strict: false
                          value: birthState
                        type: string
                        required: false
                      socialSecurityNumber:
                        example:
                          strict: false
                          value: socialSecurityNumber
                        type: string
                        required: false
                      socialSecurityNumberKey:
                        example:
                          strict: false
                          value: socialSecurityNumberKey
                        type: string
                        required: false
                      seniorityStartDate:
                        example:
                          strict: false
                          value: seniorityStartDate
                        type: string
                        required: false
                      workingDurationUnit:
                        example:
                          strict: false
                          value: workingDurationUnit
                        type: string
                        required: false
                      idVinci:
                        example:
                          strict: false
                          value: idVinci
                        type: string
                        required: false
                      hourlyRate:
                        example:
                          strict: false
                          value: hourlyRate
                        type: string
                        required: false
                      fteRatio:
                        example:
                          strict: false
                          value: fteRatio
                        type: string
                        required: false
                      employeeType:
                        type: object
                        example:
                          strict: false
                          value: employeeType
                        required: false
                      iban:
                        example:
                          strict: false
                          value: iban
                        type: string
                        required: false
                      paymentType:
                        example:
                          strict: false
                          value: paymentType
                        type: string
                        required: false
                      addressLine1:
                        example:
                          strict: false
                          value: addressLine1
                        type: string
                        required: false
                      addressLine2:
                        example:
                          strict: false
                          value: addressLine2
                        type: string
                        required: false
                      postalCode:
                        type: object
                        example:
                          strict: false
                          value: postalCode
                        required: false
                      cityOrTown:
                        example:
                          strict: false
                          value: cityOrTown
                        type: string
                        required: false
                      country:
                        example:
                          strict: false
                          value: country
                        type: string
                        required: false
                      codexIndicator:
                        example:
                          strict: false
                          value: codexIndicator
                        type: string
                        required: false
                      workingDuration:
                        example:
                          strict: false
                          value: workingDuration
                        type: string
                        required: false
                      hourlyManagedFlag:
                        example:
                          strict: false
                          value: hourlyManagedFlag
                        type: string
                        required: false
                      vehiculeClass:
                        example:
                          strict: false
                          value: vehiculeClass
                        type: string
                        required: false
              error?:
                type: object
      "404":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:NOT_FOUND
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: record XXX not found
                    type: string
                    required: false
      "500":
        description: Server error
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:SERVER ERROR
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: server error
                    type: string
                    required: false
/admin/v1/health-check:
  get:
    description: API Health Check
    headers:
      client_id:
        description: Authentication Client ID
        required: true
        type: string
      client_secret:
        description: Authentication Client Secret
        required: true
        type: string
    responses:
      "200":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      companyCode:
                        example:
                          strict: false
                          value: "690"
                        type: string
                        required: false
                      employeeERPId:
                        example:
                          strict: false
                          value: employeeERPId
                        type: string
                        required: false
                      startDate:
                        example:
                          strict: false
                          value: startDate (yyyy-MM-dd)
                        type: string
                        required: false
                      endDate:
                        example:
                          strict: false
                          value: endDate (yyyy-MM-dd)
                        type: string
                        required: false
                      actionReason:
                        example:
                          strict: false
                          value: actionReason
                        type: string
                        required: false
                      category:
                        example:
                          strict: false
                          value: category
                        type: string
                        required: false
                      employeeArea:
                        example:
                          strict: false
                          value: employeeArea
                        type: string
                        required: false
                      employeeSubArea:
                        example:
                          strict: false
                          value: employeeSubArea
                        type: string
                        required: false
                      contractType:
                        example:
                          strict: false
                          value: contractType
                        type: string
                        required: false
                      contractEndDate:
                        example:
                          strict: false
                          value: contractEndDate (yyyy-MM-dd)
                        type: string
                        required: false
                      analyticalUnit:
                        example:
                          strict: false
                          value: analyticalUnit
                        type: string
                        required: false
                      employeeGroup:
                        example:
                          strict: false
                          value: employeeGroup
                        type: string
                        required: false
                      employeeSubGroup:
                        example:
                          strict: false
                          value: employeeSubGroup
                        type: string
                        required: false
                      lastName:
                        example:
                          strict: false
                          value: contractType
                        type: string
                        required: false
                      firstName:
                        example:
                          strict: false
                          value: contractEndDate
                        type: string
                        required: false
                      gender:
                        example:
                          strict: false
                          value: analyticalUnit
                        type: string
                        required: false
                      birthDate:
                        example:
                          strict: false
                          value: birthDate
                        type: string
                        required: false
                      nationality:
                        example:
                          strict: false
                          value: nationality
                        type: string
                        required: false
                      birthCountryCode:
                        example:
                          strict: false
                          value: birthCountryCode
                        type: string
                        required: false
                      birthState:
                        example:
                          strict: false
                          value: birthState
                        type: string
                        required: false
                      socialSecurityNumber:
                        example:
                          strict: false
                          value: socialSecurityNumber
                        type: string
                        required: false
                      socialSecurityNumberKey:
                        example:
                          strict: false
                          value: socialSecurityNumberKey
                        type: string
                        required: false
                      seniorityStartDate:
                        example:
                          strict: false
                          value: seniorityStartDate
                        type: string
                        required: false
                      workingDurationUnit:
                        example:
                          strict: false
                          value: workingDurationUnit
                        type: string
                        required: false
                      idVinci:
                        example:
                          strict: false
                          value: idVinci
                        type: string
                        required: false
                      hourlyRate:
                        example:
                          strict: false
                          value: hourlyRate
                        type: string
                        required: false
                      fteRatio:
                        example:
                          strict: false
                          value: fteRatio
                        type: string
                        required: false
                      employeeType:
                        type: object
                        example:
                          strict: false
                          value: employeeType
                        required: false
                      iban:
                        example:
                          strict: false
                          value: iban
                        type: string
                        required: false
                      paymentType:
                        example:
                          strict: false
                          value: paymentType
                        type: string
                        required: false
                      addressLine1:
                        example:
                          strict: false
                          value: addressLine1
                        type: string
                        required: false
                      addressLine2:
                        example:
                          strict: false
                          value: addressLine2
                        type: string
                        required: false
                      postalCode:
                        type: object
                        example:
                          strict: false
                          value: postalCode
                        required: false
                      cityOrTown:
                        example:
                          strict: false
                          value: cityOrTown
                        type: string
                        required: false
                      country:
                        example:
                          strict: false
                          value: country
                        type: string
                        required: false
                      codexIndicator:
                        example:
                          strict: false
                          value: codexIndicator
                        type: string
                        required: false
                      workingDuration:
                        example:
                          strict: false
                          value: workingDuration
                        type: string
                        required: false
                      hourlyManagedFlag:
                        example:
                          strict: false
                          value: hourlyManagedFlag
                        type: string
                        required: false
                      vehiculeClass:
                        example:
                          strict: false
                          value: vehiculeClass
                        type: string
                        required: false
              error?:
                type: object
      "404":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:NOT_FOUND
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: record XXX not found
                    type: string
                    required: false
      "500":
        description: Server error
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:SERVER ERROR
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: server error
                    type: string
                    required: false
/admin/v1/advanced-health-check:
  get:
    description: API dependencies health check
    headers:
      client_id:
        description: Authentication Client ID
        required: true
        type: string
      client_secret:
        description: Authentication Client Secret
        required: true
        type: string
    responses:
      "200":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: array
                items:
                  type: object
                  properties:
                    depName:
                      example:
                        strict: false
                        value: anypointAMQ
                      type: string
                      required: false
                    depType:
                      example:
                        strict: false
                        value: amq
                      type: string
                      required: false
                    status:
                      example:
                        strict: false
                        value: 1
                      type: number
                      required: false
                    errorTypeNamespace:
                      example:
                        strict: false
                        value: HTTP
                      type: string
                      required: false
                    errorTypeIdentifier:
                      example:
                        strict: false
                        value: HTTP_CONNECTIVITY
                      type: string
                      required: false
                    errorDesc:
                      example:
                        strict: false
                        value: Cannot connect to AMQ
                      type: string
                      required: false
                    errorPayload:
                      type: object
                      required: false
              error?:
                type: object
      "404":
        description: Success
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:NOT_FOUND
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: record XXX not found
                    type: string
                    required: false
      "500":
        description: Server error
        body:
          application/json:
            type: object
            properties:
              header?:
                type: object
                properties:
                  apiName:
                    example:
                      strict: false
                      value: s-api-myAPI
                    type: string
                    required: false
                  apiVersion:
                    description: api version major.minor
                    example:
                      strict: false
                      value: "1.0"
                    type: string
                    required: false
                  correlationId:
                    description: correlation Id conveyed all along the Mule transaction
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
                  conversationId:
                    description: Id managed by the caller/client
                    example:
                      strict: false
                      value: ab7cdcd7-b71a-4554-87e8-61bdea42ab28
                    type: string
                    required: false
              data?:
                type: object
              error?:
                type: object
                properties:
                  type:
                    example:
                      strict: false
                      value: APP:SERVER ERROR
                    type: string
                    required: false
                  message:
                    example:
                      strict: false
                      value: server error
                    type: string
                    required: false
